baseurl = "https://docs.plugblocks.fr/"
languageCode = "en-us"
title = "PlugBlocks Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "adrien3d"
	description = "Bootstrap your next IoT project."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/PlugBlocks"

	version = "1.0.0"
	logo = "favicons/logo.png"
	favicon = "favicons/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "light-blue"
    	accent  = "teal"

    [params.font]
    	text = "Open Sans"
    	body = "Open Sans"
	    heading = "Raleway"
	    blockquote = "Gentium Basic"
	    nav = "Domine"
	    paragraph = "Open Sans"


[social]
	twitter = ""
	github  = "PlugBlocks"
	email   = "contact@plugblocks.com"


[[menu.main]]
	name   = "PlugBlocks"
	url    = "/"
	weight = 10

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 20

[[menu.main]]
	name   = "Adding content"
	url    = "adding-content/"
	weight = 30

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 40

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 50


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
